name: CICD

on:
  push:
    branches: [ main ]

jobs:
  package-and-publish-contracts:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Pack
      run: dotnet pack src/Play.Identity.Contracts/ --configuration Release -p:RepositoryUrl=https://github.com/${{github.repository_owner}}/play.identity -o packages
